data_ingestion:
  bucket_name: "mlops-anime-project-1"
  bucket_file_name:
    - "anime.csv"
    - "anime_with_synopsis.csv"
    - "animelist.csv"

model:
  embedding_size: 128
  loss: 'binary_crossentropy'
  metrics: ['mae', 'mse']
  optimizer: 'Adam'